export const SUCCESS_LOGIN_ACTION = 'SUCCESS_LOGIN_ACTION';
export const FAIL_LOGIN_ACTION = 'FAIL_LOGIN_ACTION';
export const SUCCESS_LOGOUT_ACTION = 'SUCCESS_LOGOUT_ACTION';
export const FAIL_LOGOUT_ACTION = 'FAIL_LOGOUT_ACTION';
